### ISSUE TITLE
Tuwat has problems connection to alertmanager

### ISSUE THREAD

**Issue by m4us1ne** [synyx/tuwat#184]
```
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  | 2024-01-29T07:48:15.438+0100        DPANIC        alertmanager/connector.go:88        Cannot parse: Unknown state        {"state": "active", "severity": "email"}
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  | github.com/synyx/tuwat/pkg/connectors/alertmanager.(*Connector).Collect
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  |         /home/runner/work/tuwat/tuwat/pkg/connectors/alertmanager/connector.go:88
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  | github.com/synyx/tuwat/pkg/aggregation.(*Aggregator).collect.func1
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  |         /home/runner/work/tuwat/tuwat/pkg/aggregation/aggregator.go:194
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  | panic: Cannot parse: Unknown state
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  |
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  | goroutine 24 [running]:
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  | go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x2?, {0x0?, 0x0?, 0xc0001e0720?})
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  |         /home/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:196 +0x54
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  | go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001bec30, {0xc000216c80, 0x2, 0x2})
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  |         /home/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/zapcore/entry.go:262 +0x3ec
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  | go.uber.org/zap.(*Logger).DPanic(0xc00019b280?, {0xbda1a6?, 0xc0001fa620?}, {0xc000216c80, 0x2, 0x2})
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  |         /home/runner/go/pkg/mod/go.uber.org/zap@v1.26.0/logger.go:274 +0x51
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  | github.com/uptrace/opentelemetry-go-extra/otelzap.LoggerWithCtx.DPanic({{0xcecfa0?, 0xc0001fa620?}, 0xc00019b280?}, {0xbda1a6, 0x1b}, {0xc000216c80?, 0xace8c0?, 0xc0002144e0?})
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  |         /home/runner/go/pkg/mod/github.com/uptrace/opentelemetry-go-extra/otelzap@v0.2.3/otelzap.go:302 +0x8c
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  | github.com/synyx/tuwat/pkg/connectors/alertmanager.(*Connector).Collect(0xc0001bc1c0, {0xcecfa0, 0xc0001fa620})
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  |         /home/runner/work/tuwat/tuwat/pkg/connectors/alertmanager/connector.go:88 +0x7ca
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  | github.com/synyx/tuwat/pkg/aggregation.(*Aggregator).collect.func1({0xceb400, 0xc0001bc1c0})
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  |         /home/runner/work/tuwat/tuwat/pkg/aggregation/aggregator.go:194 +0x90
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  | created by github.com/synyx/tuwat/pkg/aggregation.(*Aggregator).collect in goroutine 23
Jan 29 07:48:15 tuwat docker-compose[3537615]: tuwat  |         /home/runner/work/tuwat/tuwat/pkg/aggregation/aggregator.go:191 +0x265
Jan 29 07:48:16 tuwat docker-compose[3537615]: tuwat exited with code 2
```
Cannot parse: Unknown state        {"state": "active", "severity": "email"}
seemed to work with 1.4 previously

**Comment by BuJo** [comment]
In non-development deployments this will not panic.  Use `-environment prod` when deploying a production environment.
